[package]
name = "rr-file-processor"
version = "0.1.0"
edition = "2024"

[dependencies]
rr-parser-lib = { path = "../rr-parser-lib" }  # Local dependency
clap = { version = "4.5", features = ["derive"] }
time = { version = "0.3", features = ["formatting", "std"] }